# active spring boot profile
spring:
   profiles:
      active: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

---
# common spring boot configuration
spring:
   mvc:

      # Spring MVC View Prefix/Suffix
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

      # Path pattern used for static resources
      static-path-pattern: /assets/**

      # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/static/

   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false

   # datasource (H2 Database로 설정해줘야함)
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
      username: sa
      password: 

---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
---
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
---
# logging
logging:
  level:
    root: INFO
